### PR TITLE
fix #268 - Multisig Guild members number not increasing

### LINKED ISSUE #268: Goerli network - Multisig Guild members number not increasing
**Description**
After I've joined Multisig Guild, number of members in the Guild remained zero.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask
5. Switch to 'Goerli' network
6. Go to Multisig Guild page
7. Join the guild by approving and locking tokens

**Expected behavior**
Number of members should increase.

**Screenshots**
multisig

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

### PR DESCRIPTION
**Pull request by rulfo71**
# Description

Added logic to UseGuildMemberTotal so that in case isRepGuild is true calls to the correct contract. 

Closes #268 

Screenshot from 2022-09-12 18-34-57
Screenshot from 2022-09-12 18-36-00

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [X] My code follows the existing style of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

File: src/Modules/Guilds/Hooks/useGuildHolderTotal.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import ERC20SnapshotRep from 'contracts/ERC20SnapshotRep.json';
+import { useContractRead } from 'wagmi';
+
+const useGuildHolderTotal = (guildToken: string) => {
```
Comment (Kenny-Gin1) [inline src/Modules/Guilds/Hooks/useGuildHolderTotal.ts:4]: ❓ The naming is a bit weird here. What about calling it `useTotalGuildMembers` instead or something else that's a bit more descriptive?

File: src/Modules/Guilds/pages/LandingPage/LandingPage.tsx [hunk 2]
```diff
@@ -25,15 +27,20 @@ const GuildCardLoader = () => {
 };
 
 const GuildCardWithContent = ({ guildAddress, t }) => {
+  const { data: guildConfig } = useGuildConfig(guildAddress);
+  const { isRepGuild } = useGuildImplementationType(guildAddress);
   const { data: numberOfMembers } = useGuildMemberTotal(guildAddress);
+  const { data: numberOfHolders } = useGuildHolderTotal(guildConfig?.token);
```
Comment (Kenny-Gin1) [inline src/Modules/Guilds/pages/LandingPage/LandingPage.tsx:33]: ❓ Since these two hooks essentially do the same things but in different contracts. Would it be possible to put the conditional logic inside of the hooks and combine them into one? 🤔 

We also spare ourselves some repetitive code in `LandingPage.tsx` and API calls to the unused hook everytime.

**Review by Kenny-Gin1 — COMMENTED** [review]
Nice ⭐! Left some comments!

**Comment by dcrescimbeni** [comment]
Looks good! Agree with Kenny's comments

**Comment by Filipv95** [comment]
Hey @rulfo71 looks good, great job!

**Review by mprasanjith — APPROVED** [review]
