### PR TITLE
Fix: Contract data is null after editing action

### LINKED ISSUE #154: Contract data is null after editing action
**Description**
If you save an action and edit it after, the contract data gets set to `null`, throwing an error when trying to create the proposal.

**Steps to Reproduce**

1. Go to proposal creation
2. Add a transfer action and save
3. Edit that action and save
4. Click "Create Proposal" button
5. It throws `Unhandled Rejection (TypeError): Cannot read properties of null (reading 'getFunction')`

**Expected behavior**
Error doesn't happen and a proposal is created.

**Screenshots**
image

image

image

image

**Device Information**

- OS: Ubuntu
- Browser: Brave
- Version: v1.41.100 (July 21st, 2022)
- Device: PC

### PR DESCRIPTION
**Pull request by dcrescimbeni**
# Description

Fixes `null` value of contract interface after editing an action. Also fixed edit functionality of `transfer` action.

Removed `selectedActionContract` logic, since it was used to set a constant. Replaced places that used it for the constant instead.

Closes #154 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manual testing.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

File: src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/ERC20TransferEditor.tsx [hunk 1]
```diff
@@ -50,9 +50,22 @@ const ERC20TransferEditor: React.FC<ActionEditorProps> = ({
   onSubmit,
 }) => {
   const { t } = useTranslation();
+
+  let parsedData = useMemo(() => {
```
Comment (MiltonTulli) [inline src/Components/ActionsBuilder/SupportedActions/ERC20Transfer/ERC20TransferEditor.tsx:54]:
```suggestion
  const parsedData = useMemo(() => {

```

**Review by MiltonTulli — APPROVED** [review]

File: src/Components/ActionsModal/ActionsModal.tsx [hunk 2]
```diff
@@ -195,17 +192,21 @@ const ActionModal: React.FC<ActionModalProps> = ({
...
-    setSelectedActionContract(defaultDecodedAction.contract);
   }
 
   function saveSupportedAction(call?: DecodedCall) {
     const decodedCall = call ?? data;
-    if (!selectedAction || !decodedCall || !setSelectedActionContract) return;
+
+    const defaultDecodedAction = defaultValues[
+      decodedCall.callType
+    ] as DecodedAction;
```
Comment (Kenny-Gin1) [inline src/Components/ActionsModal/ActionsModal.tsx:202]: I would generally avoid using casting variables since it is bad TypeScript practice. Would it be feasible to either make a new interface or pick the interface from existing `DecodedAction`?

Comment (dcrescimbeni) [reply src/Components/ActionsModal/ActionsModal.tsx]: Solved!

The issue was that the default data didn't contain all the needed parameters.

**Review by Kenny-Gin1 — DISMISSED** [review]
LGTM!

**Comment by Kenny-Gin1** [comment]
You have some conflicts but otherwise looks good!

**Comment by dcrescimbeni** [comment]
> You have some conflicts but otherwise looks good!

Fixed :ok_hand:

**Review by Kenny-Gin1 — APPROVED** [review]
LGTM
