### PR TITLE
fix: Remove proposal types page and fix nft factory

### LINKED ISSUE #72: Create Guild button is disabled
**Description**
Create Guild button is disabled and doesn't respond to a click. User should be able to click on Create Guild button and to be redirected to Create Guild Page

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Create Guild button should not be present

**Expected behavior**
Create Guild button should not be visible on Landing Page 

**Screenshots**
Screenshot 2022-06-27 at 15 40 17

**Device Information**

- OS: MacOs 
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
This button should not be present and atm it redirects to broken page

### LINKED ISSUE #73: Search Guild field bar don't work
**Description**
When user click on Search Guild field bar, then can see cursor next to magnifying glass icon. But when user enter some word, that word doesn't appear in field. User should be able to submit word and to see results from search.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on Search Guild field bar
5. Enter name of Guild which you want to search

**Expected behavior**
Word which enter appear in Search Guild field bar. User can search it when press 'Enter', and should see search results.

**Actual behavior**
Word which enter don't appear in Search Guild field bar and User can't search it

**Screenshots**
Screenshot 2022-06-27 at 18 40 54

**Device Information**

- OS: MacOs
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
Expect from Search bar to work and can do some input

### LINKED ISSUE #219: Multiple 'NFT Factory' actions appear in 'Add action' module
**Description**
When I am on Proposal creation page and I click on 'Add action' button I see multiple 'NFT Factory' actions

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask and join SWPRGuild
5. Click on 'Create Proposal' button
6. Click on 'Add action' button

**Expected behavior**
Only one 'NFT Factory' option should be visible

**Screenshots**
nftfactory

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

### PR DESCRIPTION
**Pull request by rossneilson**
# Description

- Renamed create pages a little
- Removed proposal types from links since they currently have no functionality
- Add check before adding nft factory to localhost
- Removed search and create button from landing page since they currently have no functionality

Closes #219
Closes #72 
Closes #73 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

### CODE REVIEW

**Comment by Filipv95** [comment]
@rossneilson Pls ping me when is ready for QA

**Comment by rossneilson** [comment]
> @rossneilson Pls ping me when is ready for QA

Should be good now

File: src/Modules/Guilds/pages/LandingPage/LandingPage.tsx [hunk 1]
```diff
@@ -82,7 +78,7 @@ const LandingPage: React.FC = () => {
           {' '}
           <StyledLink to={`createGuild`}>{t('guilds.create')}</StyledLink>
         </StyledButton>
-      </InputContainer>
+      </InputContainer> */}
```
Comment (dcrescimbeni) [inline src/Modules/Guilds/pages/LandingPage/LandingPage.tsx:81]: Should we delete this instead of commenting it?

**Review by dcrescimbeni — COMMENTED** [review]
Some minor changes related to comments.

The code looks good :ok_hand:

File: src/Modules/Guilds/pages/LandingPage/LandingPage.tsx (hunk 1 above)
Comment (rossneilson) [reply src/Modules/Guilds/pages/LandingPage/LandingPage.tsx:82]: I think its fine to keep it in for now as the design will stay the same we are just removing it since we don't currently have the features of search and a new guild page implemented yet

Comment (rossneilson) [reply src/Modules/Guilds/pages/LandingPage/LandingPage.tsx]: Took a second look and realised this isn't doing much since the code was moved to styles so removed the comments

**Comment by rossneilson** [comment]
> @rossneilson Unable to check all thing in this PR since ATM I'm unable to create any proposal, I'm redirected to non-existing page, check screen record pls
> 
>  proposal.mp4 
> * Removed search and create button from landing page since they currently have no functionality ✔️

Thanks for pointing this out! missed this link.
I have switched around the create proposal and discussion buttons to be on this main page and now all buttons should go to the correct pages.

**Comment by Filipv95** [comment]
@rossneilson Nice, it's working now, one question
- Renamed create pages a little > what does this reffer to?
- Removed proposal types from links since they currently have no functionality :heavy_check_mark: 
- Add check before adding nft factory to localhost :heavy_check_mark: 
- Removed search and create button from landing page since they currently have no functionality :heavy_check_mark:

**Comment by rossneilson** [comment]
> @rossneilson Nice, it's working now, one question
> 
> * Renamed create pages a little > what does this reffer to?
> * Removed proposal types from links since they currently have no functionality ✔️
> * Add check before adding nft factory to localhost ✔️
> * Removed search and create button from landing page since they currently have no functionality ✔️

Ah my bad, should have added some more detail here. I was renaming the links for create proposal and discussion. Discussions are now under the /create URL since these will be the default path in future and proposal creation is under /createProposal URL

**Review by mprasanjith — DISMISSED** [review]

File: src/App.tsx [hunk 2]
```diff
@@ -47,11 +47,11 @@ const App = () => {
                   element={<ProposalPage />}
                 />
                 <Route
-                  path="/:chainName/:guildId/create/:proposalType"
+                  path="/:chainName/:guildId/createProposal"
```
[the remark this answers is not in the document]
Comment (rossneilson) [reply src/App.tsx:50]: Yes!

**Comment by Filipv95** [comment]
@rossneilson Nice, checked it again, looks good to me!

**Review by dcrescimbeni — APPROVED** [review]

File: src/App.tsx [hunk 3]
```diff
@@ -45,11 +45,11 @@ const App = () => {
                 element={<ProposalPage />}
               />
               <Route
-                path="/:chainName/:guildId/create/:proposalType"
+                path="/:chainName/:guildId/create-proposal"
```
Comment (dcrescimbeni) [inline src/App.tsx:48]: I think this should be camelCase, or switch to kebab-case for the `allProposals` route.

**Review by dcrescimbeni — DISMISSED** [review]

File: src/App.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (rossneilson) [reply src/App.tsx:48]: We will eventually use the proposal types just removing the links to the page until we have a use implemented.
And lets work out what we'll use in urls

[the remark this answers is not in the document]
Comment (rossneilson) [reply src/App.tsx:48]: Renamed all to kebab case, thanks for suggestion

**Review by dcrescimbeni — APPROVED** [review]
